apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: {{KUBE_API_SERVER_HOST}}
  bindPort: {{KUBE_API_SERVER_PORT}}
nodeRegistration:
  criSocket: unix:///run/containerd/containerd.sock
  taints:
    - effect: PreferNoSchedule
      key: node-role.kubernetes.io/master
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kubernetesVersion: {{KUBE_VERSION}}
imageRepository: registry.aliyuncs.com/google_containers
networking:
  podSubnet: 10.244.0.0/16
---
apiVersion: kubelet.config.k8s.io/v1beta1
cgroupDriver: systemd
kind: KubeletConfiguration
